###########################################################################
#
#  ZCI Build Order
#
###########################################################################
image:
    ver: 0.7


order:
    - id : all-modules  
      jdk: oraclejdk7
      env:
        SPARK_VER: 1.6.0
        HADOOP_VER: 2.3
        PROFILE: -Pspark-(SPARK_VERSION) -Phadoop-2.3 -Pscalding
        BUILD_FLAG: package -Pbuild-distr
        TEST_PROJECTS: ""
        TEST_FLAG: verify -Pusing-packaged-distr

    - id : spark-modules
      jdk: oraclejdk7
      env:
        SPARK_VER: 1.5.2 1.4.1 1.3.1 1.2.2 1.1.1
        HADOOP_VER: 2.3
        PROFILE: -Pspark-(SPARK_VERSION) -Phadoop-2.3 -Ppyspark
        BUILD_FLAG: package -DskipTests
        TEST_FLAG: verify
        TEST_PROJECTS: -pl zeppelin-interpreter,zeppelin-zengine,zeppelin-server,zeppelin-display,spark-dependencies,spark -Dtest=org.apache.zeppelin.rest.*Test,org.apache.zeppelin.spark* -DfailIfNoTests=false 

    - id : test-selenium
      jdk: oraclejdk7
      env:
        SPARK_VER: 1.6.0
        HADOOP_VER: 2.3
        PROFILE: -Pspark-(SPARK_VERSION) -Phadoop-2.3 -Ppyspark
        BUILD_FLAG: package -DskipTests
        TEST_FLAG: verify
        TEST_PROJECTS: -pl zeppelin-interpreter,zeppelin-zengine,zeppelin-server,zeppelin-display,spark-dependencies,spark -Dtest=org.apache.zeppelin.rest.*Test,org.apache.zeppelin.spark* -DfailIfNoTests=false 

    - id : add-env
      jdk: oraclejdk7
      env:
        SPARK_VER: 1.6.0
        HADOOP_VER: 2.3
        PROFILE: -Pspark-(SPARK_VERSION) -Phadoop-2.3 -Ppyspark
        BUILD_FLAG: package -DskipTests
        TEST_FLAG: verify
        ADD_ENV: test


# -------------------------------------------------------------------------
#  Set parallel jobs ( with Jenkins )
#   - Desc 
#     > Job Max   : 3 
#     > Job Range : 1 ~ 3
#
#   - Param
#     > id    : id is jenkins-job number
#     > order : [all] or [none] or [order.id]
#     > item  : image name
#   
# -------------------------------------------------------------------------
jobs:
    - id: 1
      item: spark_standalone
      orders: all-modules spark-modules
      retry: 2

    - id: 2
      item: spark_mesos
      orders: all
      retry: 2

    - id: 3
      item: spark_yarn
      orders: add-env
      retry: 2


install:
    - echo "starting install."
    - echo "mvn $BUILD_FLAG $PROFILE -B"
    - echo "install completed."


script:
    - echo "starting script."
    - echo "mvn $TEST_FLAG $PROFILE -B $TEST_PROJECTS $ADD_ENV"
    - echo "script completed."


# -------------------------------------------------------------------------
# End of File
# -------------------------------------------------------------------------
